# Generated by Django 3.2.10 on 2024-04-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='cust_image',
            field=models.ImageField(default=1, upload_to='user_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='cust_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='rating',
            field=models.FloatField(),
        ),
    ]
