# Generated by Django 3.2.10 on 2024-04-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20240405_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='cust_image',
            field=models.ImageField(upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
