# Generated by Django 3.2.10 on 2024-04-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20240405_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
